name: artefactos-ejemplo-githubactions

on: [push]

jobs:
  build_and_test:
    runs-on: windows-romell
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, build, and test
        run: |
          npm install
          npm run lint
          npm run test
          npm run build --if-present
          npm test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
      - name: Curl sonarqube
        run: curl 
  download-artifacts:
    name: Display results
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el artifact dist
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Enlistar archivos
        run: ls
